export enum PageTags {
  ITEM = 'item',
  ITEM_SPAWN = 'item-spawn',
  GE_ITEM = 'ge-item',
  SET = 'set',
  MONSTER = 'monster',
  SHOP = 'shop',
  PRAYER = 'prayer',
  SPELL = 'spell',
  RECIPE = 'recipe',
  LOCATION = 'location',
  NPC = 'npc',
  SCENERY = 'scenery',
  QUEST = 'quest',
  QUEST_GUIDE = 'quest-guide',
  ACTIVITY = 'activity',
  NEWS = 'news',
  MUSIC = 'music',
}
